apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: mvccoremariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapp
  template:
    metadata:
      labels:
        app: mvccoremariadb
        service: webapp
    spec:
      containers:
        - name: mvccoremariadb
          image: containertajamarrc.azurecr.io/mvccoremariadb:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mvccoremariadb
  labels:
    app: mvccoremariadb
    service: webapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    service: webapp

